//tealium universal tag - utag.479 ut4.0.201412191150, Copyright 2014 Tealium.com Inc. All Rights Reserved.
if(typeof utag.ut=="undefined"){utag.ut={};}
utag.ut.libloader2=function(o,a,b,c,l){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.async=true;b.src=o.src;if(o.id){b.id=o.id}
if(typeof o.cb=='function'){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}
l=o.loc||'head';c=a.getElementsByTagName(l)[0];if(c){if(l=='script'){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}
utag.DB("Attach to "+l+": "+o.src);}};try{(function(id,loader){var u=utag.o[loader].sender[id]={};u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){(function(){var nTimeToLaunch=10000;var sPixelUrl='//ms.ligatus.com/nl/track/triggerext.php?cn=trcn68849';var sCookieWithTimeStamp="ligatus_vfnl";var sVisitStartHost="vodafone.nl";var sCookiePixelFinished="ligatus_766";var nTimeStamp=null;if(VF_WA.adv.fGetCookie(sCookieWithTimeStamp)){nTimeStamp=parseInt(VF_WA.adv.fGetCookie(sCookieWithTimeStamp));}else if(location.host.indexOf(sVisitStartHost)>-1){nTimeStamp=VF_WA.nTimePageLoaded;}
if(nTimeStamp!=null&&!VF_WA.adv.fGetCookie(sCookiePixelFinished)){function fFirePixel(){var n=document.createElement('IMG');n.src=sPixelUrl;n.height='1px';n.width='1px';n.style.display='none';document.body.appendChild(n);VF_WA.adv.fSetCookie(sCookiePixelFinished,"true",null,"/",VF_WA.sTopDomain);}
var nDeltaTime=nTimeStamp+nTimeToLaunch-new Date().getTime();if(nDeltaTime>0){setTimeout(fFirePixel,nDeltaTime);}else{fFirePixel();}}})();}];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'){e=u.map[d].split(',');for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})('479','vodafone.nl-breakthrough');}catch(e){}
