//tealium universal tag - utag.618 ut4.0.201603141154, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){var indexOfArrayLowerCase=function(array,string){if(array&&string){for(var i=0,j=array.length;i<j;i++){if(typeof(array[i])==="string"&&array[i].toLowerCase()===string){return i;}}}
return-1;}
var getProductDescription=function(){var productNames=[];if(VF_WA&&VF_WA.products&&VF_WA.products.length>0){for(var i=0;i<VF_WA.products.length;i++){productNames.push(VF_WA.products[i].name);}
productNames.sort();return productNames.join();}
return"";}
var getBundelDeviceCombi=function(){var bundel=false;var device=false;if(VF_WA&&VF_WA.products&&VF_WA.products.length>0){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].type=="device"){device=true;}
if(VF_WA.products[i].type=="prepaid"&&typeof(VF_WA.products[i].name)==="string"&&VF_WA.products[i].name.toLowerCase().indexOf("you bundel")>-1){bundel=true;}}
if(device&&bundel){return 3;}else if(bundel){return 2;}else if(device){return 1;}else{return 0;}}
return 0;}
var pixels=function(){if(VF_WA&&indexOfArrayLowerCase(VF_WA.productLabels,"prepaid you")>-1){VF_WA.adv.addImg("//secure.adnxs.com/seg?add=182150&t=2");if(typeof(VF_WA.oForm.formStepName=="string")&&VF_WA.oForm.formStepName.toLowerCase()=="cart"){VF_WA.adv.addImg("//secure.adnxs.com/seg?add=3133503&t=2");VF_WA.adv.addImg("//secure.adnxs.com/px?id=569761&t=2");}
if(VF_WA.shopoid&&typeof(VF_WA.oForm.formStepName)=="string"&&VF_WA.oForm.formStepName=="orderconfirmation"){VF_WA.adv.addImg("//secure.adnxs.com/seg?add=3133508&t=2");VF_WA.adv.addImg("//secure.adnxs.com/px?id=569762&t=2");if(getBundelDeviceCombi()<1){VF_WA.adv.addAdwords({google_conversion_id:1056512399,google_conversion_language:"en",google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_label:"doIECPrpyl4Qj7Pk9wM",google_remarketing_only:false});}
if(getBundelDeviceCombi()==3){VF_WA.adv.addAdwords({google_conversion_id:1056512399,google_conversion_language:"en",google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_label:"x8EiCI_zyl4Qj7Pk9wM",google_remarketing_only:false});}else if(getBundelDeviceCombi()==2){}else if(getBundelDeviceCombi()==1){VF_WA.adv.addAdwords({google_conversion_id:1056512399,google_conversion_language:"en",google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_label:"hP4WCPG8v14Qj7Pk9wM",google_remarketing_only:false});}}}};VF_WA.adv.sendToTrackList(pixels);}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("618","vodafone.nl-breakthrough");}catch(error){utag.DB(error);}
