//tealium universal tag - utag.701 ut4.0.201611071003, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){var isPDP=false;var isPackageOverview=false;var isCart=false;var isBusiness=false;var isConsumer=false;var isPrepaid={"PDP":false,"cart":false,"confirmation":false};var isSimOnly={"PDP":false,"cart":false,"confirmation":false};var simOnlyProducts=['smart','so','scherp'];var simOnlypn=['smart','sim-only','scherp'];if(typeof VF_WA.oForm!=="undefined"&&VF_WA.oForm.formStepName&&VF_WA.oForm.formStepName.indexOf('cart')>-1)isCart=true;if(typeof VF_WA.targetAudience!=="undefined"&&(VF_WA.targetAudience=="consumer"))isConsumer=true;if(typeof VF_WA.targetAudience!=="undefined"&&(VF_WA.targetAudience=="business"||VF_WA.targetAudience=="soho/sme"))isBusiness=true;if(typeof VF_WA.pageCategory!=="undefined"&&(VF_WA.pageCategory=="product detail"||VF_WA.pageCategory=="product selection"))isPDP=true;if(typeof VF_WA.oForm!="undefined"&&VF_WA.oForm.formStepName&&VF_WA.oForm.formStepName.toLowerCase().indexOf('package overview')>-1)isPackageOverview=true;if(isPDP||isPackageOverview){if(typeof VF_WA.productCategory!=="undefined"&&VF_WA.productCategory=="prepaid")isPrepaid.PDP=true;if(typeof VF_WA.pn!=="undefined"&&VF_WA.pn.indexOf('sim-only')>-1)isSimOnly.PDP=true;if(typeof VF_WA.products!=="undefined"&&VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){for(var j=0;j<simOnlyProducts.length;j++){if(VF_WA.products[i].name.toLowerCase().indexOf(simOnlyProducts[j])>-1){isSimOnly.PDP=true;}}}}
if(!isSimOnly.PDP){for(i=0;i<simOnlypn.length;i++){if(VF_WA.pn.toLowerCase().indexOf(simOnlypn[i])>-1){isSimOnly.PDP=true;}}}
if(isPackageOverview&&isConsumer&&!isPrepaid.PDP){(function(){var e=document.createElement('script');e.type='text/javascript';e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-1/product.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}
else if(isPDP&&!isPackageOverview&&isBusiness){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-79/product.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}
else if(isPDP&&!isPackageOverview&&isSimOnly.PDP){(function(){var e=document.createElement('script');e.type='text/javascript';e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.type='text/javascript';e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-97/product.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}}
else if(isCart&&typeof VF_WA.products!=="undefined"){if(typeof VF_WA.productCategory!=="undefined"&&VF_WA.productCategory=="prepaid")isPrepaid.cart=true;if(VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].product_category2=="prepaid")isPrepaid.cart=true;}}
if(VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].name.toLowerCase().indexOf('so')>-1)isSimOnly.cart=true;if(isPrepaid.cart&&VF_WA.products[i].product_category2=="postpaid")isPrepaid.cart=false;}}
if(isSimOnly.cart){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-97/basket.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();if(typeof VF_WA.packages!=="undefined"&&VF_WA.packages.length>1){if(typeof VF_WA.products!=="undefined"&&VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].product_category2=="postpaid"&&VF_WA.products[i].name.toLowerCase().indexOf('so')==-1)isSimOnly.cart=false;}}}}
if(isConsumer&&!isSimOnly.cart&&!isPrepaid.cart){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-1/basket.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}
else if(isBusiness){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-79/basket.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}}
else if(typeof VF_WA.oForm!=="undefined"&&VF_WA.oForm.formStepName&&VF_WA.oForm.formStepName=="orderconfirmation"){if(typeof VF_WA.productCategory!=="undefined"&&VF_WA.productCategory=="prepaid")isPrepaid.confirmation=true;if(VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].product_category2=="prepaid")isPrepaid.confirmation=true;}}
if(typeof VF_WA.products!=="undefined"&&VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].name.toLowerCase().indexOf('so')>-1)isSimOnly.confirmation=true;if(isPrepaid.cart&&VF_WA.products[i].product_category2=="postpaid")isPrepaid.confirmation=false;}}
if(isSimOnly.confirmation){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-97/purchased.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();if(typeof VF_WA.packages!=="undefined"&&VF_WA.packages.length>1){if(typeof VF_WA.products!=="undefined"&&VF_WA.products){for(var i=0;i<VF_WA.products.length;i++){if(VF_WA.products[i].product_category2=="postpaid"&&VF_WA.products[i].name.toLowerCase().indexOf('so')==-1)isSimOnly.confirmation=false;}}}}
if(isConsumer&&!isSimOnly.confirmation&&!isPrepaid.confirmation){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-1/purchased.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}
else if(isBusiness){(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel-1.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();(function(){var e=document.createElement('script');e.async=true;e.src='//d2qmp7jjpd79k7.cloudfront.net/smartpixel/1-79/purchased.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("701","vodafone.nl-breakthrough");}catch(error){utag.DB(error);}
