//tealium universal tag - utag.697 ut4.0.201610311017, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){var isConsumer=false;var isPostpaid=false;var isPDP=false;var isValidCH=false;var isBusiness=false;var isPrepaid=false;if(typeof VF_WA.targetAudience!=="undefined"&&(VF_WA.targetAudience=="consumer"))isConsumer=true;if(typeof VF_WA.productCategory!=="undefined"&&(VF_WA.productCategory=="postpaid"))isPostpaid=true;if(typeof VF_WA.pageCategory!=="undefined"&&(VF_WA.pageCategory=="product detail"||VF_WA.pageCategory=="product selection"))isPDP=true;if(typeof VF_WA.channeltype!=="undefined"&&(VF_WA.channeltype=="retention"||VF_WA.channeltype=="acquisition"))isValidCH=true;if(typeof VF_WA.targetAudience!=="undefined"&&(VF_WA.targetAudience=="business"||VF_WA.targetAudience=="soho/sme"))isBusiness=true;if(typeof VF_WA.productCategory!=="undefined"&&(VF_WA.productCategory=="prepaid"))isPrepaid=true;var pixel=function(){(function(){var config={VF_122:{type:"s",id:"176745"},VF_125:{type:"s",id:"182156"},VF_132:{type:"s",id:"182155"},VF_372:{type:"c",id:"41303"},VF_485:{type:"s",id:"438103"},VF_486:{type:"c",id:"33290"},VF_487:{type:"c",id:"33285"},VF_502:{type:"c",id:"31692"},VF_503:{type:"c",id:"31693"},VF_504:{type:"c",id:"31694"},VF_505:{type:"c",id:"31695"},VF_528:{type:"c",id:"69459"},VF_923:{type:"s",id:"3036992"}};var q={s:[],c:[]};var queuepixels=function(names){for(var z=0;z<names.length;z++){var name=names[z];if(config.hasOwnProperty(name)){var pixel=config[name];q[pixel.type].push(pixel.id);}}};if(isBusiness){queuepixels(['VF_122','VF_372','VF_502','VF_503','VF_504','VF_505']);(new Image).src='//ib.adnxs.com/seg?add=279326&remove=279325';}
if(isConsumer){queuepixels(['VF_485','VF_486','VF_487','VF_528']);if(isPrepaid){(new Image).src='//ib.adnxs.com/seg?add=182155';}
if(typeof VF_WA.propositiontype!=="undefined"&&VF_WA.propositiontype.toLowerCase()=="mbb"){(new Image).src='//ib.adnxs.com/seg?add=182156';}
(new Image).src='//secure.adnxs.com/seg?add=3036992&t=2';}
var firepixels=function(){var s=q['s'],c=q['c'],seg='//ib.adnxs.com/seg?add=',add='//ib.adnxs.com/px?id=',z;if(s.length>0){(new Image).src=seg+s.join(',')+'&t=2';}
for(z=0;z<c.length;z++){(new Image).src=add+c[z]+'&t=2';}};firepixels();})();var placeNanigansImg=function(type,name,qs,id){var img=document.createElement('img');var src='//api.nanigans.com/event.php?app_id=';src+=id+'&type='+type+'&name='+name+qs;img.height='1px';img.width='1px';img.style.display='none';img.onload=function(){document.body.appendChild(img);};img.src=src;};var placeNanigansScript=function(api_call){NaN_api=api_call;(function(){var s=document.createElement('script');s.async=true;s.src='//cdn.nanigans.com/NaN_tracker.js';var h=document.getElementsByTagName('head')[0];h.appendChild(s);})();};var apiProductsMain=function(){if(VF_WA&&VF_WA.packages&&VF_WA.packages instanceof Array){var productObj={packagesku:[],qty:[],ut1:[]};$(VF_WA.packages).each(function(key,obj){productObj.packagesku.push(obj.packagesku);productObj.qty.push(obj.quantity);});return productObj;}else{return false;}};var apiCart=function(type,name,id){NaN_api=[[71056],['user','product',{'sku':VF_WA.packages[0].packagesku}]];var prods=apiProductsMain();if(prods){return[[id,''],[type,name,0,prods]];}else{return false;}};var nanigansConfiguration={product:{pixelType:'script',t:"user",n:"product",q:apiCart,id:71056},};var placeNanigans=function(type){if(!(nanigansConfiguration.hasOwnProperty(type)))return false;var conf=nanigansConfiguration[type];if(conf.pixelType&&conf.pixelType=='script'){var param=conf.q(conf.t,conf.n,conf.id);if(param){placeNanigansScript(param);}
else{placeNanigansImg(conf.t,conf.n,conf.q(),conf.id);}
return true;}};if(isConsumer&&typeof(VF_WA.packages)!=="undefined"){(function(){placeNanigans("product");})();}};if(isPDP){VF_WA.adv.sendToTrackList(pixel);if(isBusiness){}
if(isConsumer&&VF_WA.pn!=="undefined"&&(VF_WA.pn.indexOf('sim-only')>-1||VF_WA.pn.indexOf('smart')>-1||VF_WA.pn.indexOf('scherp')>-1||VF_WA.pn.indexOf('start')>-1)){(function(){var e=document.createElement('script');e.type='text/javascript';e.async=true;e.src='//d1ewibglu8fc6n.cloudfront.net/find/1-97.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);})();}};}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("697","vodafone.nl-breakthrough");}catch(error){utag.DB(error);}
