//tealium universal tag - utag.246 ut4.0.201412191150, Copyright 2014 Tealium.com Inc. All Rights Reserved.
try{if(!utag.libloader){utag.libloader=function(src,handler,a,b){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.src=src;if(typeof handler=='function'){b.handlerFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.handlerFlag){b.handlerFlag=1;handler()}};b.onload=function(){if(!b.handlerFlag){b.handlerFlag=1;handler()}};a.getElementsByTagName('head')[0].appendChild(b)}}};(function(id,loader,u){u=utag.o[loader].sender[id]={};u.ev={'view':1};u.map={};u.extend=[function(a,b){return(function(gr){function AB(gr){function e(a,d){return(d=RegExp("(^|; )"+encodeURIComponent(a)+"=([^;]*)").exec(document.cookie))?d[2]:null;}
return gr==function(){var a=e("advAB")||!1;if(a){return a;}
var d=a=50>Math.floor(100*Math.random())?"A":"B",b="90",c=new Date;c.setTime(c.getTime());b&&(b*=864E5);c=new Date(c.getTime()+b);document.cookie="advAB="+escape(d)+(b?";expires="+c.toGMTString():"")+";path=/;domain=.vodafone.nl";return(a=e("advAB")||!1)?a:!1;}();}
function BTConsumer(){return(VF_WA.targetAudience&&VF_WA.targetAudience.toLowerCase()=="consumer");}
function BTPostpaidVoice(){return(VF_WA.productCategory&&VF_WA.propositiontype)?("postpaid"==VF_WA.productCategory.toLowerCase()&&"voice"==VF_WA.propositiontype.toLowerCase()):!0;}
function MConsumer(){return(VF_WA.shoptype&&VF_WA.shoptype=="consumer");}
function BTThuis(){return VF_WA.pn&&(VF_WA.pn.indexOf("persoonlijk:thuis")>-1||VF_WA.pn.indexOf("vodafone-thuis")>-1);}
function MMyVodafone(){return VF_WA.pn&&(VF_WA.pn.indexOf("my_vodafone")>-1);}
function MPostpaidVoiceOnline(){return(VF_WA.channeltype&&VF_WA.ordertype&&VF_WA.propositiontype&&"online"==VF_WA.channeltype.toLowerCase()&&"postpaid"==VF_WA.ordertype.toLowerCase()&&"voice"==VF_WA.propositiontype.toLowerCase())}
if('string'==typeof VF_WA.pageCategory){if(BTConsumer()&&!BTThuis()){return AB(gr);}}else if('string'==typeof VF_WA.pt){if(MConsumer()&&!MMyVodafone()){return AB(gr);}}
return true;})("A");}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){var data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'){e=u.map[d].split(',');for(f=0;f<e.length;f++){data[e[f]]=b[d]}}}
(function(a1){var d1=document,c1=d1.createElement("script");c1.async=!0,c1.defer=!0,c1.src=a1,d1.getElementsByTagName("head")[0].appendChild(c1)})((iatDev=(window.location.href.indexOf("iatDev=1")>-1||document.cookie.indexOf("iatDev=1")>-1),"//"+(window.location.protocol=="http:"&&!iatDev?"h":"")+"j.flxpxl.com/31991.js?r="+Math.random()*1e16+"&m=876&a=31991"+(iatDev?"&d=1":"")))}};try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('246','vodafone.nl-breakthrough');}catch(e){}
