//tealium universal tag - utag.544 ut4.0.201602291000, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){var consent=false;if(window.dimml&&dimml.consent&&typeof(dimml.consent.get)==="function"&&dimml.consent.get()==2){consent=true;}else if(window.muc&&muc.sConsentCookie&&muc.consentTrueValue&&typeof(muc.fGetCookie)==="function"&&muc.fGetCookie(muc.sConsentCookie)==muc.consentTrueValue){consent=true;}else if(window.muc&&typeof(muc.fGetCookie)==="function"&&muc.fGetCookie("cc_analytics")=="yes"){consent=true;}
function returnSnowplowCustomContextObject(){var snowplowCustomContextObject={'sp-settings':{'opt-in':consent}};return snowplowCustomContextObject;};;(function(p,l,o,w,i,n,g){if(!p[i]){p.GlobalSnowplowNamespace=p.GlobalSnowplowNamespace||[];p.GlobalSnowplowNamespace.push(i);p[i]=function(){(p[i].q=p[i].q||[]).push(arguments)};p[i].q=p[i].q||[];n=l.createElement(o);g=l.getElementsByTagName(o)[0];n.async=1;n.src=w;g.parentNode.insertBefore(n,g)}}(window,document,"script","//d3as4l70fsmkrw.cloudfront.net/sp_2.0.2.js","snaq"));var cookieHostname='.vodafone.nl';snaq("newTracker","cf","d1mqpp146n7l7p.cloudfront.net",{cookieDomain:cookieHostname,encodeBase64:true,respectDoNotTrack:true,userFingerprint:false,pageUnloadTimer:0,forceSecureTracker:true,writeCookies:true});try{if(consent===true&&typeof VF_WA.oVisitor.onlineAccountId!=="undefined"){snaq('setUserId',VF_WA.oVisitor.onlineAccountId);}}
catch(e){}
snaq('trackPageView',document.title,returnSnowplowCustomContextObject());if(utag!==undefined&&utag.id=="vodafone.nl-breakthrough"){var pixel=function(){if(typeof VF_WA.oForm!=="undefined"&&typeof VF_WA.oForm.formStepName!=="undefined"&&VF_WA.oForm.formStepName=="orderconfirmation"&&typeof VF_WA.shopoid!=="undefined"&&typeof VF_WA.shopcity!=="undefined"&&typeof VF_WA.products!=="undefined"&&typeof VF_WA.packages!=="undefined"){var getPackageByPackageSku=function(package_sku){var foundobj=false;if(package_sku){foundobj=false;$(VF_WA.packages).each(function(key,obj){if(obj.packagesku==package_sku){foundobj=obj;}});}
return foundobj;};snaq('addTrans',VF_WA.shopoid,'Vodafone',0,0,0,VF_WA.shopcity,'','','EUR',returnSnowplowCustomContextObject());$(VF_WA.products).each(function(key,obj){var prod_package=getPackageByPackageSku(obj.package_sku);var sShopCat=obj.target_audience+":"
+obj.product_category2+":"
+prod_package.channel+":"
+prod_package.propositiontype;snaq('addItem',VF_WA.shopoid,obj.sku,obj.name,sShopCat,0,obj.quantity,'EUR',returnSnowplowCustomContextObject());});snaq('trackTrans');}}
VF_WA.adv.sendToTrackList(pixel);}
if(utag!==undefined&&utag.id=="vodafone.nl-main"){if(document.location.pathname.toLowerCase().indexOf("shop/order/orderconfirmation.jsp")>-1&&typeof VF_WA!=="undefined"&&typeof VF_WA.shopoid!=="undefined"&&typeof VF_WA.shopcity!=="undefined"&&typeof VF_WA.shopsku!=="undefined"&&typeof VF_WA.shoppr!=="undefined"&&typeof VF_WA.shopprice!=="undefined"&&typeof VF_WA.shopqn!=="undefined"&&typeof VF_WA.shoptype!=="undefined"&&typeof VF_WA.ordertype!=="undefined"&&typeof VF_WA.channeltype!=="undefined"&&typeof VF_WA.propositiontype!=="undefined"){snaq('addTrans',VF_WA.shopoid,'Vodafone',0,0,0,VF_WA.shopcity,'','','EUR',returnSnowplowCustomContextObject());var aShopSku=VF_WA.shopsku.split(";");var aShopPr=VF_WA.shoppr.split(";");var aShopPrice=VF_WA.shopprice.split(";");var aShopQn=VF_WA.shopqn.split(";");var sShopCat=VF_WA.shoptype+":"+VF_WA.ordertype+":"+VF_WA.channeltype+":"+VF_WA.propositiontype;for(var i=0;i<aShopSku.length;i++){snaq("addItem",VF_WA.shopoid,aShopSku[i],aShopPr[i],sShopCat,aShopPrice[i],aShopQn[i],'EUR',returnSnowplowCustomContextObject());}
snaq('trackTrans');}}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("544","vodafone.nl-breakthrough");}catch(error){utag.DB(error);}
